# fly.toml app configuration file generated for click-proposta-api on 2025-09-12T18:48:14Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mind-helping-api'
primary_region = 'gru'

[build]

[processes]
  app = "./start.sh node dist/server.js"

[http_service]
  internal_port = 3333
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[http_service.concurrency]
  hard_limit = 1000
  soft_limit = 800

[http_service.http_checks]
  enabled = true
  grace_period = '15s'
  interval = '30s'
  timeout = '5s'
  method = 'GET'
  path = '/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024